name: 'Minecraft Plugin Runtime Test'
description: 'A github action for testing minecraft plugins on combination of paper server versions'
branding:
  icon: 'terminal'
  color: 'green'
inputs:
  server-version:
    required: true
    description: "paper server version"
    default: '1.20.1'
  artifact-name:
    required: true
    description: "artifact"
    default: ''
  java-version:
    required: true
    description: "java version"
    default: '21'

runs:
  using: 'composite'
  steps:
    - name: Checking out Action Repository
      uses: actions/checkout@v4.1.7
      with:
        repository: sailex428/minecraft-plugin-runtime-test
        ref: main
        
    - name: Download Plugin Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: ${{ inputs.artifact-name }}
        path: server/plugins/

    - name: Setting up Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.java-version }}
        java-package: jdk
        architecture: x64

    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.3
      with:
          node-version: '20.x'

    - name: Running Test on Paper-${{ inputs.server-version }}
      shell: bash
      env: 
        SERVER_VERSION: ${{ inputs.server-version }} 
      run: npm start
